# -*- coding: utf-8 -*-
"""GPTproject1_4.16.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19dWT5AyWuzUuMXfWlqbsc20URpW1WU-n
"""

pip install openai

from openai import OpenAI
client = OpenAI(api_key="OpenAI_API_KEY")

# 파일에서 스크립트 읽기
with open("transcript.txt", "r") as f:
  transcript = f.read()

pwd

# 오픈AI의 채팅 완성 엔드포인트 호출, GPT-4 모델 사용
response = client.chat.completions.create(
    model="gpt-4-1106-preview",
    messages=[
        {"role": "system", "content": "너는 친절한 어시스턴트야."},
        {"role": "user", "content": "다음 글을 요약해줘"},
        {"role": "assistant", "content": "Yes."},
        {"role": "user", "content": transcript}
    ],
)

# 결과 출력
print(response.choices[0].message.content)

