# -*- coding: utf-8 -*-
"""GPTproject1_4_3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LGSCAJdv7nfkTrl6qzMOzUYiH4L3JxSe
"""

pip install openai

import os
os.environ["OPENAI_API_KEY"] = "OpenAI_API_KEY"

import openai # OpenAI 모듈 불러오기

# OpenAI API 키 설정
#client = OpenAI(api_key='OPENAI_API_KEY") # 사용자의 API 키로 대체해야 함

openai.api_key = os.getenv("OPENAI_API_KEY")



# ChaptGPT를 사용한 텍스트 생성 요청
response = openai.chat.completions.create(model ="gpt-3.5-turbo", messages=[{"role" : "user", "content" : "Hello Wolrd!"}])

#API 응답에서 마지막 메세지의 내용을 출력
print(response.choices[0].message.content)