# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19dWT5AyWuzUuMXfWlqbsc20URpW1WU-n
"""

pip install openai



import os
os.environ["OPENAI_API_KEY"] = "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"

import openai # OpenAI 모듈 불러오기

# OpenAI API 키 설정
#client = OpenAI(api_key='OPENAI_API_KEY") # 사용자의 API 키로 대체해야 함

openai.api_key = os.getenv("OPENAI_API_KEY")

from openai import OpenAI
client = OpenAI(api_key="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")
def ask_chatgpt(messages):
  response=client.chat.completions.create(
      model="gpt-3.5-turbo", messages=messages
  )
  return response.choices[0].message.content

import os
os.environ["OPENAI_API_KEY"] = "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"

# 파일에서 스크립트 읽기
with open("transcript.txt", "r") as f:
  transcript = f.read()

pwd

# 오픈AI의 채팅 완성 엔드포인트 호출, GPT-4 모델 사용
response = client.chat.completions.create(
    model="gpt-4-1106-preview",
    messages=[
        {"role": "system", "content": "너는 친절한 어시스턴트야."},
        {"role": "user", "content": "다음 글을 요약해줘"},
        {"role": "assistant", "content": "Yes."},
        {"role": "user", "content": transcript}
    ],
)

# 결과 출력
print(response.choices[0].message.content)

