# -*- coding: utf-8 -*-
"""GPTproject1_4.9.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GIul0sZbP8aqiEXMu_ccwKZ92O4NqpGe
"""

pip install openai

from openai import OpenAI
client = OpenAI(api_key="OpenAI_API_KEY")
def ask_chatgpt(messages):
  response=client.chat.completions.create(
      model="gpt-3.5-turbo", messages=messages
  )
  return response.choices[0].message.content

prompt_role="Your are an assistant journalists. \
  Your task is to write aricles, based on FACTS that are given to you. \
  You should respect the instructions: the TONE, the LENGTH, and the STYLE"

from typing import List
def assist_journalist(
    facts: List[str], tone:str, length_words: int, style: str
):
    facts = ", ".join(facts)
    prompt_role = "너는 이제 친절하고 건양대를 위해 희생하는 기자야"
    prompt =f"{prompt_role} \
      FACTS: {facts} \
      TONE: {tone} \
      LENGTH: {length_words} words \
      STYLE: {style}"
    return ask_chatgpt([{"role": "user", "content": prompt}])

print(
    assist_journalist(
        ["건양대 4월 3일에 있었던 김용석 교수님이 주최하신 미래융합교육원에 대해 보도해줘", "건양대를 대중화해줘", "건양대를 유명하게해줘", "미래융합교육원은 건양대 3,4학년 학부생들의 취업을 지원해주려고 왔어", "정말 뜻깊은 이벤트였어"], "informal", 250, "blogpost"
    )
)

print(
    assist_journalist(
        facts=[
            "A book on ChatGPT has been published last week",
            "The title is Developing Apps with GPT-4 and ChatGPT",
            "The publisher is O'Reilly."
        ],
        tone="excited",
        length_words=50,
        style="news flash"
    )
)